### ISSUE TITLE
No video sound and no effect on changes in logseq/custom.css

### ISSUE THREAD

**Issue by theCollectiv** [p-gentili/logseq#7]
Hi,

in the last days, I was just a little bit playing/trying out something with logseq. And I guess there are some issues with the snap version, because if install logseq via flatpak, these issues disappear.

* If you embed a video in logseq and want to play it, there is no sound
* changes in the logseq/custom.css have no (or hardly) effect (in my case I wanted to change the font)

See also: https://github.com/logseq/logseq/issues/10305

My snap version and flatpak version of logseq are both 0.9.19.

**Comment by p-gentili** [comment]
@theCollectiv please test the `edge` revision for audio playback.

**Comment by p-gentili** [comment]
@theCollectiv for what concerns custom CSS I've just tried applying a custom theme and it worked. How do you open the `custom.css` file? You should search for it from within the application, like https://discuss.logseq.com/t/how-do-i-add-a-custom-theme-to-logseq/320

**Comment by p-gentili** [comment]
Just promoted to stable a revision with the audio problem fixed. @theCollectiv please create a new issue for your CSS problem with some more details and an example.
